# Generated by Django 4.2.13 on 2025-01-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_num', models.CharField(max_length=100)),
                ('file_date', models.CharField(max_length=100)),
                ('agmt_type', models.CharField(max_length=100)),
                ('dv_url', models.CharField(max_length=100)),
                ('classdesc', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('schooldesc', models.CharField(max_length=100)),
                ('munidesc', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('bk_vol_pg', models.CharField(max_length=100)),
                ('usedesc', models.CharField(max_length=100)),
                ('calcacreag', models.CharField(max_length=100)),
                ('fairmarkettotal', models.CharField(max_length=100)),
                ('filedate', models.CharField(max_length=100)),
            ],
        ),
    ]
