# Generated by Django 4.2.13 on 2024-12-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasemap', '0002_polygonshort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polygonshort',
            options={},
        ),
    ]
