# Generated by Django 4.2.13 on 2024-12-08 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasemap', '0003_alter_polygonshort_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polygonshort',
            options={'managed': False},
        ),
    ]
