# Generated by Django 4.2.13 on 2024-12-09 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasemap', '0004_alter_polygonshort_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='polygonshort',
            table='allegheny_polys_short',
        ),
    ]
